/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "xgboost4j.h"
/* Header for class ml_dmlc_xgboost4j_java_XGBoostJNI */

#ifndef _Included_ai_h2o_xgboost4j_java_XGBoostJNI
#define _Included_ai_h2o_xgboost4j_java_XGBoostJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBGetLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBGetLastError
(JNIEnv * a0, jclass a1)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBGetLastError(a0, a1); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixCreateFromFile
 * Signature: (Ljava/lang/String;I[J)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromFile
(JNIEnv * a0, jclass a1, jstring a2, jint a3, jlongArray a4)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromFile(a0, a1, a2, a3, a4); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixCreateFromDataIter
 * Signature: (Ljava/util/Iterator;Ljava/lang/String;[J)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromDataIter
(JNIEnv * a0, jclass a1, jobject a2, jstring a3, jlongArray a4)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromDataIter(a0, a1, a2, a3, a4); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixCreateFromCSREx
 * Signature: ([J[I[F[J)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromCSREx
(JNIEnv * a0, jclass a1, jlongArray a2, jintArray a3, jfloatArray a4, jint a5, jlongArray a6)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromCSREx(a0, a1, a2, a3, a4, a5, a6); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixCreateFrom2DCSREx
 * Signature: ([J[I[F[J)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFrom2DCSREx
(JNIEnv * a0, jclass a1, jobjectArray a2, jobjectArray a3, jobjectArray a4, jint a5, jint a6, jlong a7, jlongArray a8)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFrom2DCSREx(a0, a1, a2, a3, a4, a5, a6, a7, a8); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixCreateFromCSCEx
 * Signature: ([J[I[F[J)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromCSCEx
(JNIEnv * a0, jclass a1, jlongArray a2, jintArray a3, jfloatArray a4, jint a5, jlongArray a6)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromCSCEx(a0, a1, a2, a3, a4, a5, a6); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixCreateFromCSCEx
 * Signature: ([J[I[F[J)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFrom2DCSCEx
(JNIEnv * a0, jclass a1, jobjectArray a2, jobjectArray a3, jobjectArray a4, jint a5, jint a6, jlong a7, jlongArray a8)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFrom2DCSCEx(a0, a1, a2, a3, a4, a5, a6, a7, a8); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixCreateFromMat
 * Signature: ([FIIF[J)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromMat
(JNIEnv * a0, jclass a1, jfloatArray a2, jint a3, jint a4, jfloat a5, jlongArray a6)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromMat(a0, a1, a2, a3, a4, a5, a6); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixCreateFromMatRef
 * Signature: (JIIF[J)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromMatRef
(JNIEnv * a0, jclass a1, jlong a2, jint a3, jint a4, jfloat a5, jlongArray a6)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixCreateFromMatRef(a0, a1, a2, a3, a4, a5, a6); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixSliceDMatrix
 * Signature: (J[I[J)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixSliceDMatrix
(JNIEnv * a0, jclass a1, jlong a2, jintArray a3, jlongArray a4)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixSliceDMatrix(a0, a1, a2, a3, a4); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixFree
(JNIEnv * a0, jclass a1, jlong a2)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixFree(a0, a1, a2); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixSaveBinary
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixSaveBinary
(JNIEnv * a0, jclass a1, jlong a2, jstring a3, jint a4)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixSaveBinary(a0, a1, a2, a3, a4); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixSetFloatInfo
 * Signature: (JLjava/lang/String;[F)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixSetFloatInfo
(JNIEnv * a0, jclass a1, jlong a2, jstring a3, jfloatArray a4)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixSetFloatInfo(a0, a1, a2, a3, a4); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixSetUIntInfo
 * Signature: (JLjava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixSetUIntInfo
(JNIEnv * a0, jclass a1, jlong a2, jstring a3, jintArray a4)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixSetUIntInfo(a0, a1, a2, a3, a4); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixGetFloatInfo
 * Signature: (JLjava/lang/String;[[F)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixGetFloatInfo
(JNIEnv * a0, jclass a1, jlong a2, jstring a3, jobjectArray a4)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixGetFloatInfo(a0, a1, a2, a3, a4); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixGetUIntInfo
 * Signature: (JLjava/lang/String;[[I)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixGetUIntInfo
(JNIEnv * a0, jclass a1, jlong a2, jstring a3, jobjectArray a4)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixGetUIntInfo(a0, a1, a2, a3, a4); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGDMatrixNumRow
 * Signature: (J[J)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGDMatrixNumRow
(JNIEnv * a0, jclass a1, jlong a2, jlongArray a3)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGDMatrixNumRow(a0, a1, a2, a3); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterCreate
 * Signature: ([J[J)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterCreate
(JNIEnv * a0, jclass a1, jlongArray a2, jlongArray a3)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterCreate(a0, a1, a2, a3); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterFree
(JNIEnv * a0, jclass a1, jlong a2)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterFree(a0, a1, a2); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterSetParam
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterSetParam
(JNIEnv * a0, jclass a1, jlong a2, jstring a3, jstring a4)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterSetParam(a0, a1, a2, a3, a4); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterUpdateOneIter
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterUpdateOneIter
(JNIEnv * a0, jclass a1, jlong a2, jint a3, jlong a4)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterUpdateOneIter(a0, a1, a2, a3, a4); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterBoostOneIter
 * Signature: (JJ[F[F)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterBoostOneIter
(JNIEnv * a0, jclass a1, jlong a2, jlong a3, jfloatArray a4, jfloatArray a5)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterBoostOneIter(a0, a1, a2, a3, a4, a5); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterEvalOneIter
 * Signature: (JI[J[Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterEvalOneIter
(JNIEnv * a0, jclass a1, jlong a2, jint a3, jlongArray a4, jobjectArray a5, jobjectArray a6)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterEvalOneIter(a0, a1, a2, a3, a4, a5, a6); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterPredict
 * Signature: (JJII[[F)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterPredict
(JNIEnv * a0, jclass a1, jlong a2, jlong a3, jint a4, jint a5, jobjectArray a6)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterPredict(a0, a1, a2, a3, a4, a5, a6); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterLoadModel
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterLoadModel
(JNIEnv * a0, jclass a1, jlong a2, jstring a3)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterLoadModel(a0, a1, a2, a3); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterSaveModel
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterSaveModel
(JNIEnv * a0, jclass a1, jlong a2, jstring a3)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterSaveModel(a0, a1, a2, a3); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterLoadModelFromBuffer
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterLoadModelFromBuffer
(JNIEnv * a0, jclass a1, jlong a2, jbyteArray a3)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterLoadModelFromBuffer(a0, a1, a2, a3); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterGetModelRaw
 * Signature: (J[[B)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterGetModelRaw
(JNIEnv * a0, jclass a1, jlong a2, jobjectArray a3)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterGetModelRaw(a0, a1, a2, a3); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterDumpModelEx
 * Signature: (JLjava/lang/String;I[[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterDumpModelEx
(JNIEnv * a0, jclass a1, jlong a2, jstring a3, jint a4, jstring a5, jobjectArray a6)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterDumpModelEx(a0, a1, a2, a3, a4, a5, a6); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterDumpModelExWithFeatures
 * Signature: (JLjava/lang/String;I[[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterDumpModelExWithFeatures
(JNIEnv * a0, jclass a1, jlong a2, jobjectArray a3, jint a4, jstring a5, jobjectArray a6)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterDumpModelExWithFeatures(a0, a1, a2, a3, a4, a5, a6); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterGetAttrNames
 * Signature: (I[[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterGetAttrNames
(JNIEnv * a0, jclass a1, jlong a2, jobjectArray a3)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterGetAttrNames(a0, a1, a2, a3); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterGetAttr
 * Signature: (JLjava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterGetAttr
(JNIEnv * a0, jclass a1, jlong a2, jstring a3, jobjectArray a4)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterGetAttr(a0, a1, a2, a3, a4); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterSetAttr
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterSetAttr
(JNIEnv * a0, jclass a1, jlong a2, jstring a3, jstring a4)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterSetAttr(a0, a1, a2, a3, a4); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterLoadRabitCheckpoint
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterLoadRabitCheckpoint
(JNIEnv * a0, jclass a1, jlong a2, jintArray a3)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterLoadRabitCheckpoint(a0, a1, a2, a3); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterSaveRabitCheckpoint
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterSaveRabitCheckpoint
(JNIEnv * a0, jclass a1, jlong a2)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterSaveRabitCheckpoint(a0, a1, a2); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    XGBoosterGetNumFeature
 * Signature: (J[J)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_XGBoosterGetNumFeature
(JNIEnv * a0, jclass a1, jlong a2, jlongArray a3)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_XGBoosterGetNumFeature(a0, a1, a2, a3); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    RabitInit
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_RabitInit
(JNIEnv * a0, jclass a1, jobjectArray a2)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_RabitInit(a0, a1, a2); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    RabitFinalize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_RabitFinalize
(JNIEnv * a0, jclass a1)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_RabitFinalize(a0, a1); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    RabitTrackerPrint
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_RabitTrackerPrint
(JNIEnv * a0, jclass a1, jstring a2)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_RabitTrackerPrint(a0, a1, a2); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    RabitGetRank
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_RabitGetRank
(JNIEnv * a0, jclass a1, jintArray a2)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_RabitGetRank(a0, a1, a2); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    RabitGetWorldSize
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_RabitGetWorldSize
(JNIEnv * a0, jclass a1, jintArray a2)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_RabitGetWorldSize(a0, a1, a2); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    RabitVersionNumber
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_RabitVersionNumber
(JNIEnv * a0, jclass a1, jintArray a2)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_RabitVersionNumber(a0, a1, a2); }

/*
 * Class:     ml_dmlc_xgboost4j_java_XGBoostJNI
 * Method:    RabitAllreduce
 * Signature: (Ljava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_ai_h2o_xgboost4j_java_XGBoostJNI_RabitAllreduce
(JNIEnv * a0, jclass a1, jobject a2, jint a3, jint a4, jint a5)
{ return Java_ml_dmlc_xgboost4j_java_XGBoostJNI_RabitAllreduce(a0, a1, a2, a3, a4, a5); }

#ifdef __cplusplus
}
#endif
#endif
