FROM nvidia/cuda:8.0-devel-centos6
MAINTAINER h2oai "h2o.ai"

ARG JENKINS_UID='2117'
ARG JENKINS_GID='2117'
ARG H2O_BRANCH='h2o3'
ARG PYTHON_VERSIONS='2.7,3.5,3.6'

RUN \
    curl -s https://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo | sed 's/\$releasever/6/g' > /etc/yum.repos.d/epel-apache-maven.repo && \
    yum install -y centos-release-scl && \
    yum install -y devtoolset-3-toolchain python27 python33-python-virtualenv zip java-1.8.0-openjdk-devel apache-maven wget git unzip

# Install all Python versions
COPY scripts/install_python_version_centos /usr/sbin/
RUN \
    chmod a+x /usr/sbin/install_python_version_centos && \
    sync && \
    /usr/sbin/install_python_version_centos

RUN \
    # Check that gcc is of correct version
    source scl_source enable devtoolset-3 && \
    if [ "$(gcc --version | head -1)" != 'gcc (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)' ]; then exit 1; fi && \
    # Install CMake
    wget http://www.cmake.org/files/v3.5/cmake-3.5.2.tar.gz && \
    tar -xvzf cmake-3.5.2.tar.gz && \
    cd cmake-3.5.2/ && \
    ./configure && \
    make && \
    make install && \
    cd .. && \
    rm -rf cmake-3.5.2 && \
    if [ "$(cmake --version | head -1)" != 'cmake version 3.5.2' ]; then exit 1; fi

# Add the Jenkins user
RUN \
    groupadd -g ${JENKINS_GID} jenkins && \
    useradd jenkins -m -u ${JENKINS_UID} -g jenkins

COPY scripts/warmup-caches /usr/bin/
RUN \
    chmod a+x /usr/bin/warmup-caches

USER jenkins
RUN \
    source /opt/rh/python27/enable && \
    source /opt/rh/devtoolset-3/enable && \
    /usr/bin/warmup-caches

USER root