FROM harbor.h2o.ai/opsh2oai/h2o-3-xgboost-build-centos6:latest
MAINTAINER h2oai "h2o.ai"

RUN \
    yum install -y xz libffi-devel bzip2-devel ncurses-devel gdbm-devel xz-devel sqlite-devel readline-devel zlib-devel libuuid-devel && \
    yum groupinstall -y 'Development Tools' && \
    cd /usr/src && \
    curl -LO 'https://www.openssl.org/source/openssl-1.1.0h.tar.gz' && \
    tar -xf openssl-1.1.0h.tar.gz && \
    cd openssl-1.1.0h && \
    ./config shared --prefix=/usr/local/openssl11 --openssldir=/usr/local/openssl11 && \
    make && \
    make install && \
    cd .. && \
    rm -rf openssl-1.1.0h* && \
    curl -LO 'https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz' && \
    tar -xf Python-3.7.0.tar.xz

COPY scripts/Setup.dist.patched /usr/src/Python-3.7.0/Modules/Setup.dist

RUN \
    cd /usr/src/Python-3.7.0 && \
    LDFLAGS="-Wl,-rpath=/usr/local/openssl11/lib" ./configure --prefix=/usr/local/python37 --with-openssl=/usr/local/openssl11 --with-system-ffi && \
    make altinstall && \
    ln -s /usr/local/python37/bin/*3.7* /usr/local/bin && \
    cd .. && \
    rm -rf Python-3.7.0* && \
    source /opt/rh/python27/enable && \
    virtualenv --python=python3.7 /envs/xgb-env-py3.7 && \
    . /envs/xgb-env-py3.7/bin/activate && \
    pip install pip wheel setuptools --upgrade && \
    deactivate
