FROM nvidia/cuda:8.0-devel-ubuntu14.04
MAINTAINER h2oai "h2o.ai"

ARG JENKINS_UID='2117'
ARG JENKINS_GID='2117'

RUN \
    apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:webupd8team/java && \
    apt-get update && \
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
    apt-get install -y zip oracle-java8-installer maven wget git unzip python

RUN \
    # Install CMake
    wget http://www.cmake.org/files/v3.5/cmake-3.5.2.tar.gz && \
    tar -xvzf cmake-3.5.2.tar.gz && \
    cd cmake-3.5.2/ && \
    ./configure && \
    make && \
    make install && \
    cd .. && \
    rm -rf cmake-3.5.2 && \
    if [ "$(cmake --version | head -1)" != 'cmake version 3.5.2' ]; then exit 1; fi

# Add the Jenkins user
RUN \
    groupadd -g ${JENKINS_GID} jenkins && \
    useradd jenkins -m -u ${JENKINS_UID} -g jenkins